map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 2.5
raytrace_range: 3.5

publish_voxel_map: false
transform_tolerance: 0.25
meter_scoring: false

footprint: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]
footprint_padding: 0.05

plugins:
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  observation_sources: scan
  scan: {sensor_frame: front_laser, data_type: LaserScan, topic: front/scan, marking: true, clearing: false, min_obstacle_height: -2.0, max_obstacle_height: 2., obstacle_range: 3.5, raytrace_range: 2.0}

inflater_layer:
 inflation_radius: 0.3
